from .area import MasterArea
from .faculty import MasterFaculty
from .feature import MasterFeature
from .framework import MasterFramework
from .industry import MasterIndustry
from .industry_classification import MasterIndustryClassification
from .occupation import MasterOccupation
from .programming_experience import MasterProgrammingExperience
from .programming_language import MasterProgrammingLanguage
from .qualification import MasterQualification
from .school import MasterSchool
from .skill import MasterSkill
