"""very_first_migrate

Revision ID: 87feae834c14
Revises: 
Create Date: 2023-12-13 04:52:07.053728

"""
from alembic import op
import sqlalchemy as sa
import app



# revision identifiers, used by Alembic.
revision = '87feae834c14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False, comment='企業ID'),
    sa.Column('name', sa.String(length=63), nullable=False, comment='名称'),
    sa.Column('max_scouts', sa.Integer(), nullable=False, comment='契約スカウト数'),
    sa.Column('contract_expiration_date', sa.DateTime(timezone=True), nullable=False, comment='契約満了日'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('company_id', name=op.f('uq_companies_company_id'))
    )
    op.create_index(op.f('ix_companies_is_disabled'), 'companies', ['is_disabled'], unique=False)
    op.create_table('m_areas',
    sa.Column('value', sa.String(length=63), nullable=False, comment='エリア'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='表示順'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_areas'))
    )
    op.create_table('m_faculties',
    sa.Column('value', sa.String(length=63), nullable=False, comment='学部'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='表示順'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_faculties'))
    )
    op.create_table('m_features',
    sa.Column('value', sa.String(length=63), nullable=False, comment='特徴'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='表示順'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_features'))
    )
    op.create_table('m_frameworks',
    sa.Column('value', sa.String(length=63), nullable=False, comment='フレームワーク'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='表示順'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_frameworks'))
    )
    op.create_table('m_industry_classifications',
    sa.Column('value', sa.String(length=63), nullable=False, comment='業種分類'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='表示順'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_industry_classifications'))
    )
    op.create_table('m_occupations',
    sa.Column('value', sa.String(length=63), nullable=False, comment='職種'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='表示順'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_occupations'))
    )
    op.create_table('m_programming_experiences',
    sa.Column('value', sa.String(length=63), nullable=False, comment='プログラミング経験'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='表示順'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_programming_experiences'))
    )
    op.create_table('m_programming_languages',
    sa.Column('value', sa.String(length=63), nullable=False, comment='プログラミング言語'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='表示順'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_programming_languages'))
    )
    op.create_table('m_qualifications',
    sa.Column('value', sa.String(length=63), nullable=False, comment='資格'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='表示順'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_qualifications'))
    )
    op.create_table('m_schools',
    sa.Column('value', sa.String(length=63), nullable=False, comment='学校'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='表示順'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_schools'))
    )
    op.create_table('m_skills',
    sa.Column('value', sa.String(length=63), nullable=False, comment='スキル'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='表示順'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_skills'))
    )
    op.create_table('managed_students',
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生ID'),
    sa.Column('account_name', sa.String(length=150), nullable=False, comment='アカウント名'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='表示名'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_managed_students')),
    sa.UniqueConstraint('student_id', name=op.f('uq_managed_students_student_id'))
    )
    op.create_index(op.f('ix_managed_students_is_disabled'), 'managed_students', ['is_disabled'], unique=False)
    op.create_table('disclosed_students',
    sa.Column('company_id', sa.Integer(), nullable=False, comment='企業ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_disclosed_students_company_id_companies')),
    sa.ForeignKeyConstraint(['student_id'], ['managed_students.student_id'], name=op.f('fk_disclosed_students_student_id_managed_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disclosed_students'))
    )
    op.create_index(op.f('ix_disclosed_students_is_disabled'), 'disclosed_students', ['is_disabled'], unique=False)
    op.create_table('jobs',
    sa.Column('company_id', sa.Integer(), nullable=False, comment='企業ID'),
    sa.Column('status', app.models.column_types.int_enum.IntEnum(), nullable=False, comment='状態'),
    sa.Column('applied_date', sa.DateTime(timezone=True), nullable=False, comment='申請日時'),
    sa.Column('is_use_published_job', sa.Boolean(create_constraint=True), nullable=False, comment='公開求人にするか否か'),
    sa.Column('publication_start_date', sa.DateTime(timezone=True), nullable=False, comment='掲載開始'),
    sa.Column('publication_end_date', sa.DateTime(timezone=True), nullable=False, comment='掲載終了'),
    sa.Column('employment_status', app.models.column_types.int_enum.IntEnum(), nullable=False, comment='雇用形態'),
    sa.Column('graduation_year', sa.Integer(), nullable=False, comment='卒業年'),
    sa.Column('m_occupation_id', sa.Integer(), nullable=False, comment='職種'),
    sa.Column('number_of_people_hired', sa.Integer(), nullable=False, comment='採用人数'),
    sa.Column('initiatives_to_prevent_passive_smoking', app.models.column_types.int_enum.IntEnum(), nullable=False, comment='就業場所における受動喫煙防止の取組'),
    sa.Column('skill_level', app.models.column_types.int_enum.IntEnum(), nullable=False, comment='スキルレベル'),
    sa.Column('salary_form', app.models.column_types.int_enum.IntEnum(), nullable=False, comment='給与形態'),
    sa.Column('min_salary_amount', sa.Integer(), nullable=False, comment='最小給与額'),
    sa.Column('max_salary_amount', sa.Integer(), nullable=False, comment='最大給与額'),
    sa.Column('salary_supplement', sa.String(length=255), nullable=False, comment='給与補足'),
    sa.Column('commuting_time_supplement', sa.String(length=255), nullable=False, comment='勤務時間補足'),
    sa.Column('job_title', sa.String(length=63), nullable=False, comment='求人タイトル'),
    sa.Column('job_image', sa.String(length=255), nullable=False, comment='求人トップ画像'),
    sa.Column('application_requirements', sa.String(length=255), nullable=False, comment='募集要項'),
    sa.Column('job_description', sa.String(length=255), nullable=False, comment='仕事内容'),
    sa.Column('target_people', sa.String(length=255), nullable=False, comment='対象となる方'),
    sa.Column('worklocation', sa.String(length=255), nullable=False, comment='勤務地'),
    sa.Column('contract_period', sa.String(length=127), nullable=False, comment='契約期間'),
    sa.Column('trial_period', app.models.column_types.int_enum.IntEnum(), nullable=False, comment='試用期間'),
    sa.Column('salary_increment', sa.String(length=127), nullable=False, comment='昇給'),
    sa.Column('bonus', sa.String(length=127), nullable=False, comment='賞与'),
    sa.Column('overtime_work', sa.Boolean(), nullable=False, comment='時間外勤務'),
    sa.Column('overtime_work_free_input', sa.String(length=255), nullable=False, comment='時間外勤務の自由入力'),
    sa.Column('holidays_or_vacation', sa.String(length=255), nullable=False, comment='休日・休暇'),
    sa.Column('social_insurance', sa.String(length=127), nullable=False, comment='社会保険'),
    sa.Column('welfare', sa.String(length=255), nullable=False, comment='福利厚生'),
    sa.Column('training_system', sa.String(length=255), nullable=False, comment='研修制度'),
    sa.Column('selection_method', sa.String(length=255), nullable=False, comment='選考方法'),
    sa.Column('submitted_document', sa.String(length=255), nullable=False, comment='提出書類'),
    sa.Column('employment_promotion_law', sa.String(length=255), nullable=False, comment='雇用推進法明示項目'),
    sa.Column('contact_information', sa.String(length=255), nullable=False, comment='問い合わせ先'),
    sa.Column('corporate_pr', sa.String(length=255), nullable=False, comment='企業PR'),
    sa.Column('original_content1_title', sa.String(length=127), nullable=False, comment='オリジナルコンテンツ１のタイトル'),
    sa.Column('original_content1_text', sa.Text(), nullable=False, comment='オリジナルコンテンツ１の本文'),
    sa.Column('original_content2_title', sa.String(length=127), nullable=False, comment='オリジナルコンテンツ２のタイトル'),
    sa.Column('original_content2_text', sa.Text(), nullable=False, comment='オリジナルコンテンツ２の本文'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_jobs_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_is_disabled'), 'jobs', ['is_disabled'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('m_industries',
    sa.Column('industry_classification_id', sa.Integer(), nullable=False, comment='業種分類ID'),
    sa.Column('value', sa.String(length=63), nullable=False, comment='業種'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='表示順'),
    sa.ForeignKeyConstraint(['industry_classification_id'], ['m_industry_classifications.id'], name=op.f('fk_m_industries_industry_classification_id_m_industry_classifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_industries'))
    )
    op.create_table('templates',
    sa.Column('company_id', sa.Integer(), nullable=False, comment='企業の一意の識別子'),
    sa.Column('use_case', app.models.column_types.int_enum.IntEnum(), nullable=False, comment='スカウトテンプレート or メッセージテンプレート'),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False, comment='TechFUL+text型'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_templates_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_index(op.f('ix_templates_is_disabled'), 'templates', ['is_disabled'], unique=False)
    op.create_index(op.f('ix_templates_use_case'), 'templates', ['use_case'], unique=False)
    op.create_table('areas',
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='求人ID'),
    sa.Column('m_area_id', sa.Integer(), nullable=False, comment='エリアマスターの一意の識別子'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_areas_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_areas'))
    )
    op.create_index(op.f('ix_areas_is_disabled'), 'areas', ['is_disabled'], unique=False)
    op.create_table('commuting_times',
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='求人ID'),
    sa.Column('commuting_time_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('commuting_time_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_commuting_times_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commuting_times'))
    )
    op.create_index(op.f('ix_commuting_times_is_disabled'), 'commuting_times', ['is_disabled'], unique=False)
    op.create_table('employment_management_status',
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='求人ID'),
    sa.Column('employment_management_status', app.models.column_types.int_enum.IntEnum(), nullable=False, comment='企業における雇用管理に関する状況'),
    sa.Column('free_input', sa.String(length=1000), nullable=False, comment='TechFUL+text型'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_employment_management_status_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employment_management_status'))
    )
    op.create_index(op.f('ix_employment_management_status_is_disabled'), 'employment_management_status', ['is_disabled'], unique=False)
    op.create_table('favorite_jobs',
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='企業ID'),
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='求人ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_favorite_jobs_company_id_companies')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_favorite_jobs_job_id_jobs')),
    sa.ForeignKeyConstraint(['student_id'], ['managed_students.student_id'], name=op.f('fk_favorite_jobs_student_id_managed_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorite_jobs'))
    )
    op.create_index(op.f('ix_favorite_jobs_is_disabled'), 'favorite_jobs', ['is_disabled'], unique=False)
    op.create_table('features',
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='求人ID'),
    sa.Column('m_feature_id', sa.Integer(), nullable=False, comment='特徴マスターの一意の識別子'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_features_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_features'))
    )
    op.create_index(op.f('ix_features_is_disabled'), 'features', ['is_disabled'], unique=False)
    op.create_table('frameworks',
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='求人ID'),
    sa.Column('m_framework_id', sa.String(length=32), nullable=False, comment='求人ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_frameworks_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frameworks'))
    )
    op.create_index(op.f('ix_frameworks_is_disabled'), 'frameworks', ['is_disabled'], unique=False)
    op.create_table('job_templates',
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='求人ID'),
    sa.Column('template_id', sa.String(length=36), nullable=False, comment='テンプレートID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_templates_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_job_templates_template_id_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_templates'))
    )
    op.create_index(op.f('ix_job_templates_is_disabled'), 'job_templates', ['is_disabled'], unique=False)
    op.create_table('occupational_ability_status',
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='求人ID'),
    sa.Column('occupational_ability_status', app.models.column_types.int_enum.IntEnum(), nullable=False, comment='職業能力開発・向上に関する状況'),
    sa.Column('free_input', sa.String(length=1000), nullable=False, comment='TechFUL+text型'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_occupational_ability_status_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_occupational_ability_status'))
    )
    op.create_index(op.f('ix_occupational_ability_status_is_disabled'), 'occupational_ability_status', ['is_disabled'], unique=False)
    op.create_table('programming_languages',
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='求人ID'),
    sa.Column('m_programming_language_id', sa.String(length=32), nullable=False, comment='求人ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_programming_languages_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programming_languages'))
    )
    op.create_index(op.f('ix_programming_languages_is_disabled'), 'programming_languages', ['is_disabled'], unique=False)
    op.create_table('recruitment_flows',
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='企業の一意の識別子'),
    sa.Column('free_input', sa.String(length=1000), nullable=False, comment='TechFUL+text型'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_recruitment_flows_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruitment_flows'))
    )
    op.create_index(op.f('ix_recruitment_flows_is_disabled'), 'recruitment_flows', ['is_disabled'], unique=False)
    op.create_table('recruitment_status',
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='求人ID'),
    sa.Column('recruitment_status', app.models.column_types.int_enum.IntEnum(), nullable=False, comment='募集採用に関する状況'),
    sa.Column('free_input', sa.String(length=1000), nullable=False, comment='TechFUL+text型'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_recruitment_status_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruitment_status'))
    )
    op.create_index(op.f('ix_recruitment_status_is_disabled'), 'recruitment_status', ['is_disabled'], unique=False)
    op.create_table('selections',
    sa.Column('company_id', sa.Integer(), nullable=False, comment='企業ID'),
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='求人ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生の一意の識別子'),
    sa.Column('is_scout_refuse', sa.Boolean(), nullable=False),
    sa.Column('route', app.models.column_types.int_enum.IntEnum(), nullable=False, comment='スカウト経由（スカウト非公開求人） or 公開求人経由（スカウト公開求人）'),
    sa.Column('step', app.models.column_types.int_enum.IntEnum(), nullable=False),
    sa.Column('scheduled_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=False, comment='TechFUL+text型'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_selections_company_id_companies')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_selections_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['managed_students.student_id'], name=op.f('fk_selections_student_id_managed_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_selections'))
    )
    op.create_index(op.f('ix_selections_is_disabled'), 'selections', ['is_disabled'], unique=False)
    op.create_index(op.f('ix_selections_route'), 'selections', ['route'], unique=False)
    op.create_index(op.f('ix_selections_step'), 'selections', ['step'], unique=False)
    op.create_table('skills',
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='求人ID'),
    sa.Column('m_skill_id', sa.String(length=32), nullable=False, comment='求人ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_skills_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_index(op.f('ix_skills_is_disabled'), 'skills', ['is_disabled'], unique=False)
    op.create_table('messages',
    sa.Column('selection_id', sa.String(length=36), nullable=False, comment='選考ID'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='企業ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生ID'),
    sa.Column('send_date', sa.DateTime(timezone=True), nullable=False, comment='送信日'),
    sa.Column('is_unread', sa.Boolean(), nullable=False, comment='未読か'),
    sa.Column('message_type', app.models.column_types.int_enum.IntEnum(), nullable=False, comment='メッセージの種類'),
    sa.Column('body', sa.Text(), nullable=False, comment='本文'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_messages_company_id_companies')),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], name=op.f('fk_messages_selection_id_selections')),
    sa.ForeignKeyConstraint(['student_id'], ['managed_students.student_id'], name=op.f('fk_messages_student_id_managed_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_is_disabled'), 'messages', ['is_disabled'], unique=False)
    op.create_table('reactions',
    sa.Column('company_id', sa.Integer(), nullable=False, comment='企業ID'),
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='求人ID'),
    sa.Column('selections_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生の一意の識別子'),
    sa.Column('activity_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened', sa.Boolean(), nullable=False),
    sa.Column('agreed', sa.Boolean(), nullable=False),
    sa.Column('replied', sa.Boolean(), nullable=False),
    sa.Column('viewed', sa.Boolean(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_reactions_company_id_companies')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_reactions_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selections_id'], ['selections.id'], name=op.f('fk_reactions_selections_id_selections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['managed_students.student_id'], name=op.f('fk_reactions_student_id_managed_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reactions'))
    )
    op.create_index(op.f('ix_reactions_is_disabled'), 'reactions', ['is_disabled'], unique=False)
    op.create_table('message_tempfiles',
    sa.Column('selection_id', sa.String(length=36), nullable=False, comment='選考ID'),
    sa.Column('message_id', sa.String(length=36), nullable=False, comment='メッセージID'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='ファイル名'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='ファイルパス'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('created_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.Column('updated_user_id', sa.Integer(), nullable=False, comment='作成ユーザーID'),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True, comment='削除日時'),
    sa.Column('disabled_user_id', sa.Integer(), nullable=True, comment='作成ユーザーID'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_tempfiles_message_id_messages')),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], name=op.f('fk_message_tempfiles_selection_id_selections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_tempfiles'))
    )
    op.create_index(op.f('ix_message_tempfiles_is_disabled'), 'message_tempfiles', ['is_disabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_tempfiles_is_disabled'), table_name='message_tempfiles')
    op.drop_table('message_tempfiles')
    op.drop_index(op.f('ix_reactions_is_disabled'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_messages_is_disabled'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_skills_is_disabled'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_selections_step'), table_name='selections')
    op.drop_index(op.f('ix_selections_route'), table_name='selections')
    op.drop_index(op.f('ix_selections_is_disabled'), table_name='selections')
    op.drop_table('selections')
    op.drop_index(op.f('ix_recruitment_status_is_disabled'), table_name='recruitment_status')
    op.drop_table('recruitment_status')
    op.drop_index(op.f('ix_recruitment_flows_is_disabled'), table_name='recruitment_flows')
    op.drop_table('recruitment_flows')
    op.drop_index(op.f('ix_programming_languages_is_disabled'), table_name='programming_languages')
    op.drop_table('programming_languages')
    op.drop_index(op.f('ix_occupational_ability_status_is_disabled'), table_name='occupational_ability_status')
    op.drop_table('occupational_ability_status')
    op.drop_index(op.f('ix_job_templates_is_disabled'), table_name='job_templates')
    op.drop_table('job_templates')
    op.drop_index(op.f('ix_frameworks_is_disabled'), table_name='frameworks')
    op.drop_table('frameworks')
    op.drop_index(op.f('ix_features_is_disabled'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_favorite_jobs_is_disabled'), table_name='favorite_jobs')
    op.drop_table('favorite_jobs')
    op.drop_index(op.f('ix_employment_management_status_is_disabled'), table_name='employment_management_status')
    op.drop_table('employment_management_status')
    op.drop_index(op.f('ix_commuting_times_is_disabled'), table_name='commuting_times')
    op.drop_table('commuting_times')
    op.drop_index(op.f('ix_areas_is_disabled'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_templates_use_case'), table_name='templates')
    op.drop_index(op.f('ix_templates_is_disabled'), table_name='templates')
    op.drop_table('templates')
    op.drop_table('m_industries')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_disabled'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_disclosed_students_is_disabled'), table_name='disclosed_students')
    op.drop_table('disclosed_students')
    op.drop_index(op.f('ix_managed_students_is_disabled'), table_name='managed_students')
    op.drop_table('managed_students')
    op.drop_table('m_skills')
    op.drop_table('m_schools')
    op.drop_table('m_qualifications')
    op.drop_table('m_programming_languages')
    op.drop_table('m_programming_experiences')
    op.drop_table('m_occupations')
    op.drop_table('m_industry_classifications')
    op.drop_table('m_frameworks')
    op.drop_table('m_features')
    op.drop_table('m_faculties')
    op.drop_table('m_areas')
    op.drop_index(op.f('ix_companies_is_disabled'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
